change font color to black
redpanda-data/docs-ui pull request #60
Opened 2023-08-08 15:35 UTC by Deflaimun

2023-08-08 17:55 UTC, JakeSCahill commented
This depends if we are going with our style guide (what's in the blog) or what we currently have for our prod docs.

Either way, this change does not resolve all the font color differences. For example, the footer font color in our prod docs is not black.

2023-08-10 15:14 UTC, JakeSCahill commented
@Deflaimun let's handle all font changes in this PR.

2023-08-16 18:25 UTC, JakeSCahill requested changes
looks good. I prefer to use rem for those fonts so they are relative to the root.

Also not sure where the `footer-links-list-item-detail` class is defined and whether we need it.

2023-08-16 18:25 UTC, JakeSCahill commented on src/css/footer.css
> +  font-size: 12px;
```suggestion
  font-size: 0.75rem;
```

2023-08-16 18:25 UTC, JakeSCahill commented on src/css/footer.css
> +  font-size: 16px;
```suggestion
  font-size: 0.9rem;
```

2023-08-16 18:25 UTC, JakeSCahill commented on src/css/header.css
> +  font-size: 13px;
```suggestion
  font-size: 0.75rem;
```

2023-08-16 18:25 UTC, JakeSCahill commented on src/partials/footer-content.hbs
> +                        <li class="footer-links-list-item"><a class="footer-links-list-item-detail" aria-label="Capabilities" target="_blank" href="https://redpanda.com/platform-capabilities">Capabil
where is this class defined?

2023-08-16 18:32 UTC, Deflaimun commented on src/css/footer.css
> +.footer-links-list-item-detail {
@JakeSCahill

2023-08-16 19:02 UTC, Deflaimun commented on src/css/footer.css
> +.footer-links-list-item-detail {
The idea with this class is to make the max-height property. I couldn't do it with the li because that would make the link unclickable.

2023-08-17 07:20 UTC, JakeSCahill approved these changes

2023-08-17 07:20 UTC, merged